version: '3.8'

services:
    mysql:
        restart: always
        image: mysql:8.0
        platform: linux/x86_64
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/data:/var/lib/mysql
